# 1-write Numpy prgoram to test whether none of elements of a given array is zero

In [1]:
import numpy as np

In [2]:
x =np.array ([[2,5,4],[4,8,7]])

In [3]:
print(x)

[[2 5 4]
 [4 8 7]]


In [4]:
print(np.all(x))

True


# 2- write Numpy prgoram to test whether any of elements of a given array is non-zero

In [5]:
z =np.array ([[0,5,4],[4,8,0]])

In [6]:
print(z)

[[0 5 4]
 [4 8 0]]


In [7]:
print(np.all(z))

False


# 3- write Numpy prgoram to create an element-wise comparsion(equal,equal within a tolerance of two given)

In [8]:
x = np.array([[2,5,6,7]])
z = np.array([[1,5,3,7]])

In [9]:
print(x)
print(z)

[[2 5 6 7]]
[[1 5 3 7]]


In [10]:
x==z

array([[False,  True, False,  True]])

# 4- write a numpy program to create an array of 10 zeros,10 ones,10 fives

In [11]:
A = np.zeros(10)
print(A)
B = np.ones(10)
print(B)
C = np.ones(10)*5
print(C)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 5- write a Numpy program to create an array of the integers from 30 to 70

In [12]:
new_arr = np.arange(30,71)

In [13]:
new_arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

# 6- write a Numpy program to create a 3*3 identity matrix

In [14]:
i = np.eye(3,3)

In [15]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 7-write a Numpy program to generate a random number between 0 and 1

In [16]:
print(np.random.uniform(0,1))

0.22999647155906555


# 8-write a Numpy program to generate an array of 15 random numbers from a standard normal distribution

In [17]:
print(np.random.randn(3,5))

[[ 0.19184883  1.80297271  0.4098818   0.23450627  0.09925089]
 [-1.13510666  0.14886654  0.30339986  0.78364318 -0.5883613 ]
 [-0.48843415 -0.42667234 -1.10461029 -1.06194232 -1.34105389]]


In [18]:
print(np.random.randn(5,3))


[[ 0.13602387  0.29216314  0.22232958]
 [ 1.82493282 -2.46519723  0.11440098]
 [-0.79280099 -0.17831854  0.48014567]
 [-0.61279182 -2.20579093  0.41517469]
 [ 1.10586891  0.46785737  0.19753355]]


# 9-write a Numpy program to create a vector with values ranging from 15 to 55 and print all values except the first and the last

In [19]:
Q = np.arange(15,56)

In [20]:
print(Q)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [21]:
print(Q[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


# 10- write a Numpy program to create a vector of length 5 filled with arbitrary from 0 to 10

In [22]:
print(np.random.randint(0,11,5))

[4 8 1 7 1]


# 11-write a Numpy program to create a 10*10 matrix, in which the elements on the borders will be equal to 1 , and inside 0.

In [23]:
Z= np.ones((10,10))
Z[1:-1,1:-1] =0


In [24]:
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 12-write a Numpy program to create 5*5 zero matrix on the main diagonal equal 1,2,3,4,5

In [25]:
 np.diag([1,2,3,4,5])


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 13-Write a program to create 4*4 matrix in which 0 and 1 are staggered,with zeros on the main diagonal

In [26]:
F = np.zeros((4,4))
F[::2 ,1::2] = 1
F[1::2, ::2] = 1
F

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

# 14- write a Numpy program to save two given arrays into a single file in compressed format(.npz format )and load it


In [27]:
import os 

In [28]:
x = np.arange(10)
z = np.arange(11,20)
print(x)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [29]:
np.savez("array.npz",x=x,z=z)
with np.load("array.npz") as data:
    x2=data["x"]
    z2=data["z"]

In [30]:
print(x2)
print(z2)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


# 15- write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values select.

In [31]:
np.random.seed(10)
print(np.random.rand(40))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


# 16-write a NumPy program to extract all numbers from given array which are less and greater than a specified number.

In [32]:
z =np.array ([[7.1,5,4],[4,8,9.6],[5.2,6.2,4]])

In [33]:
print(z)

[[7.1 5.  4. ]
 [4.  8.  9.6]
 [5.2 6.2 4. ]]


In [34]:
n = 6
print("elements is greater than " , z[z>n])

elements is greater than  [7.1 8.  9.6 6.2]


In [35]:
n = 7
print("elements is less than" , z[z<n])

elements is less than [5.  4.  4.  5.2 6.2 4. ]
